const ADD_DISTANCE = "ADD_DISTANCE"
const RESET_DISTANCE = "RESET_DISTANCE"

const SET_START = "SET_START"
const RESET_START = "RESET_START"

export default {
    ADD_DISTANCE,
    RESET_DISTANCE,
    SET_START,
    RESET_START
}
